version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - APP_ENV=dev
      - XDEBUG_MODE=off
      - SYMFONY_PHPUNIT_VERSION=9.5

  caddy:
    volumes:
      - ./public:/app/public:ro
      - ./:/app
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
