services:
  # Główny serwis naszego agenta
  app:
    build: 
      context: .
      target: dev # Możemy zdefiniować etap deweloperski w Dockerfile
    volumes:
      - .:/app
      - /app/var 
    env_file:
      - .env.dev
    tty: true # Pozwala na interakcję z terminalem
    working_dir: /app