# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(GEMINI_API_KEY): ''
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    env(LOTTO_API_KEY): ''
    lotto_api_key: '%env(LOTTO_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Service\AgentTools\LottoToolInterface:
            tags: ['app.lotto_agent_tool']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\AgentTools\ToolRegistry:
        arguments:
            $tools: !tagged_iterator app.lotto_agent_tool




    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
